config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'stocks#index'
  resources :users, only: [:index, :edit, :update]

  get 'stocks', to: 'stocks#edit'
  resources :stocks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true, uniqueness: true

  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  
  def index
    @stocks = Stock.all.order(out_stock: :asc)
  end

  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)
    if @stock.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: "在庫情報を登録しました" }
        format.json
      end
    else
      @stocks = Stock.includes(:user)
      flash.now[:alert] = '商品名を入力してください。'
      render :new
    end
  end
    
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy
    redirect_to root_path, notice: "在庫情報を削除しました"
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def update
    @stock = Stock.find(params[:id])
    if @stock.update(stock_params)
      redirect_to root_path, notice: "在庫情報を編集しました"
    else
      render :edit
    end
  end

  private
  def stock_params
    params.require(:stock).permit(:name, :url, :sets_register, :sets_current, :pcs, :pcs_daily, :pcs_current, :last_purchase, :out_stock, :howmany_stock, :price, :price_1day, user_ids: []).merge(user_id: current_user.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PetSuppliesManagement 〜ペット用品の在庫管理〜
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body

    .notifications
      - flash.each do |key, value|
        = content_tag(:div, value, class: key)

    .Header
      .Header__logo
        %h1 Pet Supplies Management
        %h2 〜 ペット用品の在庫管理 〜

    = yield

app/views/stocks/_form.html.haml
.Form
  = form_with model: @stock, local: true do |f|
    .Form__product
      = f.label :name, "商品名"
      = f.text_field :name
      = f.label :url,"url"
      = f.url_field :url, placeholder: "（購入サイト等url）"
    .Form__stocks
      = f.label :sets_current,"在庫数(パッケージ)"
      = f.number_field :sets_current, id: "sets_current"
      = f.label :pcs,"　何個入"
      = f.number_field :pcs, id: "pcs"
      = f.label :pcs_daily,"　1日の使用個数"
      = f.number_field :pcs_daily, id: "pcs_daily"
    .Form__price
      = f.label :price,"価格(円)"
      = f.text_field :price, placeholder: "（半角数字）", id: "price"
      = f.label :price_1day,"　1日コスト(円)"
      = f.text_field :price_1day, placeholder: "（自動計算）", id:"price_1day"
    .Form__last_purchase
      = f.label :last_purchase,"直近購入日(カウント開始日)"
      = f.date_field :last_purchase, id: "last_purchase"
    .Form__out_stock
      = f.label :out_stock,"在庫がなくなる日"
      = f.date_field :out_stock, id:"out_stock"
    .Form__register
      = f.submit "登録"

app/views/stocks/edit.html.haml
.Title
  在庫編集
  = render "form"

.Return
  = link_to "トップページに戻る", root_path

app/views/stocks/index.html.haml
.Contents
  .Contents__top
    = current_user.name
    = image_tag "tare1.png", alt: "ペット画像", class: "image", width: "110px", height: "90px"
    .menu
      = link_to edit_user_path(current_user), class: "menu__btn" do
        = icon('fas', 'user', class: "menu__btn--icon")
        %span<>
        User
      = link_to new_stock_path(current_user), class: "menu__btn" do
        = icon('fas', 'paw',  class: "menu__btn--icon")
        %span<>
        Stock

  .Contents__stock
    %h1 在庫状況
    - @stocks.each do |stock|
      .stock
        = stock.name
        　価格:
        = stock.price
        円
        　在庫数:
        = stock.sets_current
        　1日コスト:
        = stock.price_1day
        円
        　在庫がなくなる日:
        = stock.out_stock.strftime("%Y/%m/%d")

        %ul.stock__list        
          %li
            = link_to '編集', edit_stock_path(stock.id), method: :get
            = link_to '削除', stock_path(stock.id), method: :delete, data: {confirm: "本当に削除しますか？"}

app/views/stocks/new.html.haml
.Title
  在庫登録
  = render "form"
  
.Return
  = link_to "トップページに戻る", root_path

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'